### ISSUE TITLE
Baseline speed of behat tests

### ISSUE THREAD

**Issue by simesy** [openeuropa/drupal-module-template#10] opened 2018-07-17 06:44 UTC
My behat is quite slow, and it has nothing to do with the actual tests. If I remove all tests it takes about 1 minute. This is from inside the container. 

```
/var/www/html # ./vendor/bin/behat
No scenarios
No steps
1m5.22s (19.93Mb)
```

Is this the experience others are having? My grumphp and phpunit run fine enough.

**Comment by dxvargas** [comment] 2019-02-26 17:55
@simesy nothing compared with your values. With present the scenario:
`# ./vendor/bin/behat
.
1 scenario (1 passed)
1 step (1 passed)
0m0.66s (19.27Mb)
`
Can you try again with release 0.1.0?

**Comment by dxvargas** [comment] 2019-03-20 11:27
Closing since feedback was given and it's not reproducible.

**Closed by dxvargas** 2019-03-20 11:27 UTC
